### ISSUE TITLE
Detail view should directly show comments

### ISSUE THREAD

**Issue by koppor** [ultimate-comparisons/ultimate-comparison-BASE#10]
Instead of using the fly over thing as here ...

![grabbed_20170201-190215](https://cloud.githubusercontent.com/assets/1366654/22519571/0b34cd66-e8b1-11e6-8661-24c60ea8a4ab.png)

...the detail page should display the text next to the labels.

**Comment by kleinech** [comment]
Feature is optional:
Settings -> Details page -> check "Display tooltip text next to labels in the details page"
(check "Display Template" and visit the "Template" details page)

**Comment by koppor** [comment]
Can this be the default?

Am 20.02.2017 12:15 schrieb "kleinech" <notifications@github.com>:
