### ISSUE TITLE
Rate Limit for GitHub

### ISSUE THREAD

**Issue by hueneburg** [ultimate-comparisons/ultimate-comparison-BASE#103]
When pulling information from GitHub it is possible to hit a rate limit. This is signified with following error:

    GET https://api.github.com/repos/ultimate-comparisons/ultimate-comparison-BASE/commits 403 (Forbidden)
    "{
     "message": "API rate limit exceeded for 129.69.213.210. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
     "documentation_url": "https://developer.github.com/v3/#rate-limiting"
    }"

caused by #39

**Comment by koppor** [comment]
Using an OAuth token solves that.
