### ISSUE TITLE
Version link is wrong

### ISSUE THREAD

**Issue by bartsch-dev** [ultimate-comparisons/ultimate-comparison-BASE#111]
The version link at the bottom is wrong (misssing the v)

'https://github.com/ultimate-comparisons/ultimate-comparison-BASE/releases/tag/1.0.0' vs. 'https://github.com/ultimate-comparisons/ultimate-comparison-BASE/releases/tag/v1.0.0'

**Comment by koppor** [comment]
Pull Request?
