### ISSUE TITLE
Not working on Windows 10

### ISSUE THREAD

**Issue by baderas** [ultimate-comparisons/ultimate-comparison-BASE#12]
I am trying to run it on Windows 10. npm, gulp, java are all installed and in PATH.

The error is :
```
> npm start

> ultimate-comparison-framework@1.0.0 start C:\Users\xxx\GIT\ultimate-TSDB-comparison
> npm run gulp:compile && npm run webpack:start


> ultimate-comparison-framework@1.0.0 gulp:compile C:\Users\xxx\GIT\ultimate-TSDB-comparison
> node_modules/gulp/bin/gulp.js default

Der Befehl "node_modules" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xxx\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "gulp:compile"
npm ERR! node v7.7.0
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ultimate-comparison-framework@1.0.0 gulp:compile: `node_modules/gulp/bin/gulp.js default`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ultimate-comparison-framework@1.0.0 gulp:compile script 'node_modules/gulp/bin/gulp.js default'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ultimate-comparison-framework package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node_modules/gulp/bin/gulp.js default
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ultimate-comparison-framework
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ultimate-comparison-framework
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2017-03 -01T16_57_46_076Z-debug.log 
```

But node_modules are existing and NODE_PATH is set correctly (according to http://stackoverflow.com/questions/9587665/nodejs-cannot-find-installed-module-on-windows).

The following commands were used to setup (draft for a new readme :)):
1. Install [chocolatey](https://chocolatey.org/)
2. Install [node.js](https://nodejs.org/en/): `choco install nodejs` (admin cmd)
3. Install [Java JDK8](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html): `choco install jdk8` (admin cmd)
4. Install [pandoc](http://pandoc.org/installing.html): `choco install pandoc` (admin cmd)
5. Update npm: `npm.cmd install -g npm` (admin cmd)
6. Install Gulp: `npm install --global gulp-cli`
7. `npm install`
8. `npm start` (starts the web page)
9. [Setup automatic deployment of `www` directory using Travis CI](https://github.com/ultimate-comparisons/ultimate-comparison-BASE/wiki/Build-and-deploy-project-with-Travis-CI)

Tested with cmd and msys2-bash.

Maybe related to https://github.com/npm/npm/issues/4040?

**Comment by koppor** [comment]
Is following a possible workaround: [Ubuntu Bash on Windows](https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/)?

**Comment by baderas** [comment]
This may work, but a native working build on windows would be nice.
