### ISSUE TITLE
Explicit demonstration page

### ISSUE THREAD

**Issue by koppor** [ultimate-comparisons/ultimate-comparison-BASE#134]
After inclusion of the README.md as homepage (http://ultimate-comparisons.github.io/ultimate-comparison-BASE/), the possibility to provide a demonstration was lost.

I can point to a PR (.g., http://ultimate-comparisons.github.io/ultimate-comparison-BASE/prs/rewrite/) in the README md, but what if the PR is lost?

I see following alternatives:

- build all tags and offer it as sub-directory at `gh-pages`
- Always build the `master` branch and offer it as sub-directory at `gh-pages`
- Create a `demo` branch and offer it as sub-directory at `gh-pages`

I opt for the first one as this follows the inspiration of tags and the master branch could be broken sometimes.

**Comment by hueneburg** [comment]
It can be found under [https://ultimate-comparisons.github.io/ultimate-comparison-BASE/demo/](https://ultimate-comparisons.github.io/ultimate-comparison-BASE/demo/). I will add a point in the index.md.
