### ISSUE TITLE
Treat README-THING.template

### ISSUE THREAD

**Issue by koppor** [ultimate-comparisons/ultimate-comparison-BASE#142]
`README-THING.template` used to exist, but does not exist anymore. However, it is linked from README.md:

![grafik](https://user-images.githubusercontent.com/1366654/36422626-225e926e-163d-11e8-9d25-92ffca19ba5d.png)

**Comment by kleinech** [comment]
README-THING.template is replace by lib/uc/README.md and must be change to be self-contained

**Comment by kleinech** [comment]
The reference from the main README.md can be removed.

**Comment by koppor** [comment]
Removed it at https://github.com/ultimate-comparisons/ultimate-comparison-BASE/commit/170783abcfcb517f3084668ab04f98a342c4cca1.
