### ISSUE TITLE
Criteria-type "url" does not work

### ISSUE THREAD

**Issue by schneisn** [ultimate-comparisons/ultimate-comparison-BASE#151]
Defining a criterion-type as "url" and showing it in the table breaks the table 😆 
The example has a "Download" section with the type "url".
Markdown-file:
```
## Download
- https://github.com/randombit/botan/archive/2.0.0.zip

```
Comparison.yml:
```
  - Download:
      detail: true
      search: false
      table: false
      type: url
```

E.g. the table without a "url" type:
![image](https://user-images.githubusercontent.com/29998690/37556163-40ecffb8-29f2-11e8-9eeb-d3c669ec9fe6.png)
With "url" type:
![image](https://user-images.githubusercontent.com/29998690/37556167-4f9362dc-29f2-11e8-839d-c5c6621622c1.png)

If the url is only shown in the detail view, the detail view does not work correctly anymore
Without "url" type:
![image](https://user-images.githubusercontent.com/29998690/37556182-8619cc24-29f2-11e8-8dff-7cef0a185325.png)
With "url" type:
Only the "Description"-section is shown
![image](https://user-images.githubusercontent.com/29998690/37556190-bb794ef8-29f2-11e8-915c-a3af58d67566.png)

**Comment by koppor** [comment]
This field is currently used for the header. Format:

    Name - URL

In the examples, it is used as the `id` field. We change the type to `uct` (for ultimate comparision title or "ollyspezial")

To fix your issue, change the type to `markdown`. Please enclose the URL in `<>`. Officially, GitHub flavored markdown does not support autlinking: https://github.github.com/gfm/#example-595

**Comment by koppor** [comment]
Please report back if it works.

**Comment by schneisn** [comment]
Works with `type: markdown` and enclosing the url in `<>` 👍
