### ISSUE TITLE
Make links in tag descriptions clickable

### ISSUE THREAD

**Issue by bartsch-dev** [ultimate-comparisons/ultimate-comparison-BASE#20]
Make links in tag descriptions clickable (`MIT` tag in the `License` categorie):

![link](https://cloud.githubusercontent.com/assets/15333371/23767006/388c04b0-0507-11e7-930c-46fc907463d6.PNG)

**Comment by koppor** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version.
