### ISSUE TITLE
Table gets scrambled when viewing the details 

### ISSUE THREAD

**Issue by bartsch-dev** [ultimate-comparisons/ultimate-comparison-BASE#24]
### Steps to reproduce:
1. open an ultimate comparison (eg. https://ultimate-comparisons.github.io/ultimate-IoT-platform-comparison/)
2. open the details of any item
3. watch the table get scrambled in the background

This only happens if the table is __not__ ordered specifically (ie clicking on the header).
This also doesn't happen with the base example.
When fixing #23 this should be fixed as an side effect.

**Comment by koppor** [comment]
Is this issue still valid?

**Comment by bartsch-dev** [comment]
Nope, it has already been fixed.
