### ISSUE TITLE
Display the version of the ultimate-comparison-BASE

### ISSUE THREAD

**Issue by bartsch-dev** [ultimate-comparisons/ultimate-comparison-BASE#25]
I think it would be helpful if the version of the `ultimate-comparison-BASE` is displayed at the bottom of the page.

**Comment by koppor** [comment]
Idea: `version.json`

    {
        "date": "2016-01-01",
        "commit": "3e61c709d8b758f79a8fbd71bda28829cbb8803b",
        "link": "https://github.com/ultimate-comparisons/ultimate-comparison-BASE/commit/3e61c709d8b758f79a8fbd71bda28829cbb8803b"
    }

In the UI:

- shorten commit id to 8 characters
- display: [3e61c709](https://github.com/ultimate-comparisons/ultimate-comparison-BASE/commit/3e61c709d8b758f79a8fbd71bda28829cbb8803b) (2016-01-01)

**Comment by koppor** [comment]
Should be fixed in master
