### ISSUE TITLE
Possibility to set a Tag depending on the last GitHub Commit of a Repository

### ISSUE THREAD

**Issue by baderas** [ultimate-comparisons/ultimate-comparison-BASE#39]
E.g., for giving a stale-state for the developement of a software, it would be nice if UC could automatically set a tag (e.g., "stale", "in developement") based on the last commit of a given repository and a comparison date.
Therefore a link to a git repo would be given and a date. UC would then automatically recreate the tag (once per day for example.).

**Comment by bartsch-dev** [comment]
> Possibility to set a Tag depending on the last GitHub Commit of a Repository
... or the last release of a repository.

**Comment by kleinech** [comment]
Am 29.04.2017 um 14:51 schrieb Christian Bartsch:
