### ISSUE TITLE
Tags in the search should be the same color as in the table

### ISSUE THREAD

**Issue by bartsch-dev** [ultimate-comparisons/ultimate-comparison-BASE#52]
current version: 176c5937 (2017-04-25)

Tags in the search should be the same color as in the table
<img width="506" alt="crit" src="https://cloud.githubusercontent.com/assets/15333371/25482261/50fbdac8-2b51-11e7-9958-faa74000dfeb.PNG">

**Comment by koppor** [comment]
We use [select2](https://select2.github.io/). Thus, we cannot easily fix this.

Maybe during a rewrite.
