### ISSUE TITLE
Details are ugly

### ISSUE THREAD

**Issue by bartsch-dev** [ultimate-comparisons/ultimate-comparison-BASE#64]
Currently the detail page is quite ugly (in this one the tooltips are enabled, but it doesn't look much better without them):
![details](https://cloud.githubusercontent.com/assets/15333371/25722148/5541a8ca-3113-11e7-8824-341ac2b80e03.PNG)

I think it would be better if each criteria would inherit half the width (2 columns).

**Comment by kleinech** [comment]
Fix with css-grid update
