### ISSUE TITLE
Sort the tags

### ISSUE THREAD

**Issue by bartsch-dev** [ultimate-comparisons/ultimate-comparison-BASE#66]
Currently the order of the tags of each entry is defined in the markdown file. It would be better if they are sorted automatically.

**Comment by hueneburg** [comment]
How should they be sorted? I can think of the following possibilities

 - Alphabetically
 - Good to Bad
 - Bad to Good

The two latter would be implemented via a ``weight`` attribute in table.json with descending and ascending order. If no weight is added, descending and ascending refer to alphabetically.

If you have some other ideas, let me know.

**Comment by hueneburg** [comment]
closed via PR
