### ISSUE TITLE
Use pastell tones instead of bright colors

### ISSUE THREAD

**Issue by koppor** [ultimate-comparisons/ultimate-comparison-BASE#79]
Follow up to #13, #14, and https://github.com/ultimate-comparisons/ultimate-comparison-BASE/pull/48#issuecomment-304681949

The current auto coloring uses the same colors across tags.

Example (taken from https://ultimate-comparisons.github.io/ultimate-tex-makers-comparison/)

![grafik](https://user-images.githubusercontent.com/1366654/27470506-88c31014-57f4-11e7-925d-62512fb2073c.png)

- Why is `geddit3` the same category as `all`?
- red is a signal color and should be avoided - see e.g., discussion at http://munsell.com/color-blog/why-that-color-signal/ for coloring

- [ ] I would propose to have automated coloring assigning a single color for each category. color1 for supported tools, color2 for detect changes in tex, etc.

- [ ] For the colors itself, I opt for pastel tones. They are not as bright (and disturbing) as the current colors. See for example http://www.templatemonsterblog.de/pastellfarbendes-webdesign/ for a long discussion and some example colors.

More information about colors and web sites: https://www.w3.org/WAI/gettingstarted/tips/designing and Section 1.4.3 of https://www.w3.org/WAI/WCAG20/quickref/#qr-visual-audio-contrast-contrast1

**Comment by hueneburg** [comment]
solved in #82
