### ISSUE TITLE
Make links of the tag description in the tooltip clickable

### ISSUE THREAD

**Issue by muelletr** [ultimate-comparisons/ultimate-comparison-BASE#81]
Links of the tag descriptions (`table.json` file) are not clickable in the tooltip.

In the detail view the link (description for `MIT`) is clickable
![details](https://user-images.githubusercontent.com/14543255/27731227-766787cc-5d8c-11e7-9127-18b2f2414d8c.JPG)

but in the tooltip the link is not clickable.
![tooltip](https://user-images.githubusercontent.com/14543255/27731226-7666df0c-5d8c-11e7-81e5-c150771b9c79.JPG)

**Comment by hueneburg** [comment]
Closed with commit on July 5th.
