### ISSUE TITLE
Rearrange table after selecting columns in the settings

### ISSUE THREAD

**Issue by muelletr** [ultimate-comparisons/ultimate-comparison-BASE#85]
Large tables should be rearranged after selecting all columns in the settings.

**Before changing columns in the settings:**
![table](https://user-images.githubusercontent.com/14543255/27897877-2c96fc68-6223-11e7-8033-559ca28c8564.png)

**After selecting all columns in the settings:**
![table-with-alle-columns](https://user-images.githubusercontent.com/14543255/27897879-2c98979e-6223-11e7-91d0-b5116b76468a.png)

**Table should look like this:**
![table-with-alle-columns-rearranged](https://user-images.githubusercontent.com/14543255/27897878-2c9859aa-6223-11e7-910c-b6c7ae25143c.png)

**Comment by kleinech** [comment]
Has already been fixed with comit bc4032b35cc632060578b013dd580828d4d38a47.
