### ISSUE TITLE
Automatically update all ultimate-comparsions upon a new release

### ISSUE THREAD

**Issue by koppor** [ultimate-comparisons/ultimate-comparison-BASE#86]
In case a new version of `-BASE` is released, all comparisons hosted at https://github.com/ultimate-comparisons should be **automatically** be updated. Is that possible?

Refs https://github.com/ultimate-comparisons/ultimate-comparison-BASE/issues/59

**Comment by kleinech** [comment]
Automatically update all comparisons that are listed in an update file:
- Repositories must contain an ultimcate-comparison update `Deploy key`

**Comment by koppor** [comment]
Please try to also update https://github.com/TSDBBench/Ultimate-TSDB-Comparison.
