### ISSUE TITLE
Sticky header with CSS

### ISSUE THREAD

**Issue by koppor** [ultimate-comparisons/ultimate-comparison-BASE#87]
The current solution for sticky headers is based on JavaScript. Please check whether it is possible to revert that solution and to use `position. sticky` (See http://gedd.ski/post/position-sticky/). If that is impossible, please describe why.

Browser support is listed there: http://caniuse.com/#feat=css-sticky

Demo: http://html5-demos.appspot.com/static/css/sticky.html

Refs https://github.com/ultimate-comparisons/ultimate-comparison-BASE/pull/31

**Comment by koppor** [comment]
Hint: Use `top` css in addition - see https://stackoverflow.com/a/43707215/873282

**Comment by kleinech** [comment]
#wontfix

Sticky headers do not work together with table header `display: table-header-group;`.

Other display styles do synchronize the dynamic width between the table header and the table data.

A css-grid solution might come handy in the future but the feature `display: subgrid` has been excluded for Firefox and Chrome in the first Version of css-grid (https://github.com/w3c/csswg-drafts/issues/958).
