### ISSUE TITLE
Update critiera.json by harvesting existing markdown

### ISSUE THREAD

**Issue by koppor** [ultimate-comparisons/ultimate-comparison-BASE#89]
Possible development step of an ultimate comparison

- Harvest tools
- Evaluate tools
- Come up with new criteria
- Evaluate the tools

And then, the selection boxes are configured (possible values, ...)

With that approach, sometimes, not all criteria can be filtered.

Example:

![grafik](https://user-images.githubusercontent.com/1366654/28201006-54c93a0a-686f-11e7-9a6e-e32863e8fc11.png)

It would be good if there was a script **updating** [cirtieria.json](https://github.com/ultimate-comparisons/ultimate-comparison-BASE/blob/master/comparison-configuration/criteria.json) out of [comparison-elements](https://github.com/ultimate-comparisons/ultimate-comparison-BASE/tree/master/comparison-elements). Thus, an existing `criteria.json` should not be simply overwritten, but updated.

**Comment by kleinech** [comment]
Closed with #124
