### ISSUE TITLE
Compare with bpmnmatrix.github.io

### ISSUE THREAD

**Issue by koppor** [ultimate-comparisons/ultimate-comparison-BASE#97]
https://bpmnmatrix.github.io/ looks pretty neat.

And the code *very* simple --> https://github.com/bpmnmatrix/bpmnmatrix.github.io

What can we use from there for our framework? Maybe some HTML and CSS magic?

**Comment by hueneburg** [comment]
Won't be included because this style can only be applied if we know exactly how many columns we will have but cannot be used for a more general solution with an arbitrary amount of columns.
